<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
<?php
// module/Album/view/album/album/index.phtml:
$title = 'My albums';
$this->headTitle ( $title );
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
	<p>
		<a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add
			new album</a>
	</p>

	<table class="table">
		<tr>
			<th>Title</th>
			<th>Artist</th>
			<th>&nbsp;</th>
		</tr> <?php foreach ($albums as $album) : ?>
 <tr>
			<td><?php echo $this->escapeHtml($album->title);?></td>
			<td><?php echo $this->escapeHtml($album->artist);?></td>
			<td><a
				href="<?php
			
echo $this->url ( 'album', array (
					'action' => 'edit',
					'id' => $album->id 
			) );
			?>">Edit</a> <a
				href="<?php
			
echo $this->url ( 'album', array (
					'action' => 'delete',
					'id' => $album->id 
			) );
			?>">Delete</a></td>
		</tr>
 <?php endforeach; ?>
 </table>
</body>
</html>